version: '3'

services:
    influx:
        image: influxdb:latest
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        volumes:
            - ./data/influxdb:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=bl3pbot
        logging:
          driver: "none"

    grafana:
        depends_on:
            - influx
        image: jsdidierlaurent/rpi-grafana:latest
        ports:
            - "3000:3000"
        links:
          - influx
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=secret
        volumes:
            - ./data/grafana:/var/lib/grafana

    bl3p:
        build: .
        command: make
        volumes:
            - .:/app/bl3pbot
        ports:
            - "8000:8000"
        links:
          - grafana
          - influx
        depends_on:
            - grafana
            - influx
        # tty: true
