# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ma3',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='session',
            name='ma1',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='session',
            name='ma2',
            field=models.PositiveSmallIntegerField(default=26),
        ),
    ]
