# Generated by Django 2.0.2 on 2018-02-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20180121_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pair',
            field=models.CharField(default='BTCEUR', max_length=16),
        ),
    ]
